-## Put comments here that give an overall description of what your
-## functions do
-
-## Write a short comment describing this function
-## makeCacheMatrix creates a special matrix object, and then cacheSolve 
-## calculates the inverse of the matrix.
-## If the inverse of the matrix has been calculated, it will instead 
-## find it in the cache and return it.
-
-makeCacheMatrix <- function(x = matrix()) {
-    inv <- NULL
-    set <- function(y) {
-        x <<- y
-        inv <<- NULL
-    }
-    get <- function() x
-    setinverse <- function(inverse) inv <<-inverse
-    getinverse <- function() inv
-    list(set = set, get = get,
-         setinverse = setinverse,
-         getinverse = getinverse)
-}
-
-## The function cacheSolve returns the inverse of a matrix A created with
-## the function makeCacheMatrix (above)
-## If the inverse is in the cache, the function cacheSolve retrieves it. If not,
-## it calculates it and returns it.
-
-cacheSolve <- function(x, ...) {
-    ## Return a matrix that is the inverse of 'x'
-    inv <- x$getinverse()
-    if (!is.null(inv)) {
-        message("getting cached inverse matrix")
-        return(inv)
-    } else {
-        inv <- solve(x$get())
-        x$setinverse(inv)
-        return(inv)
-    }
-}
